README.org
aider.el defines aider in the provide. aidermacs failed for me. Unsure if your config.el example needs to be swapped too.
=> Update use-package call

aidermacs.el
The built in VC package can get the git root without requiring magit. The function `aider-magit-show-last-commit` checks if magit is available before running, so it is an optional dependency.
=> Remove dependency on magit

aidermacs-backend-vterm.el
- local bindings vterm-shell, vterm-buffer-name
- open vterm in another window instead of current window
=> fix(aidermacs-bacend-vterm.el): avoid changing vterm global variables

aidermacs-backend-vterm.el
This is an improved version of #10.
The key thing is that we need to make sure the two variables we want to dynamically bind should be declared by `defvar`, otherwise it will be treated as lexical binding.
Beside, we suggest we stick with the default `(vterm)` instead of `(vterm-other-window)`.
In case the user want to configure the window opening strategy, they can always configure `display-buffer-alist`, an example is as following:
the following config in user's config ensures the window open as another window. The user can configure it to whatever they want, for example my personal preference would be to open it at another tab.
```emacs-lisp
(add-to-list 'display-buffer-alist
`("\\*aidermacs.*\\*"
(display-buffer-pop-up-window)))
```
=> fix(vterm): use dynamic binding instead of global binding.

aidermacs-backend-comint.el
Now that aider has option to control input and output, we don't need to use the "dumb" terminal to disable fancy input. This let's us fix the message:
Detected dumb terminal, disabling fancy input and pretty output.
That will show up if that term is used.
=> Remove "Detected dumb terminal" from output

aidermacs.el
Currently, if you try to send a command to Aider and the session is not running, it will just raise an error. Instead what we can do is just start the session for the user.
When I want to add a file to aider with the old flow, it would look something like this:
1. run `aidermacs-add-current-file` via the transient.
2. it tells me that aider is not running
3. run `aidermacs-run`. This switches me away from my current buffer
4. Switch back to my buffer
5. Run `aidermacs-add-current-file` again.
After this change, running `aidermacs-add-current-file` will just work the first time.
=> Run Aider automatically if it is not already running

aidermacs.el
When invoking `aidermacs-explain-symbol-under-point`, I noticed that aidermacs was detecting the symbol incorrectly. This seems to be a side-effect of the `(aidermacs-add-current-file)` call, which causes `(thing-at-point 'symbol)` to be called in the context of the aider buffer instead of the source buffer. Calling `(aidermacs-add-current-file)` after reading symbol fixes the problem for me.
Same for `aidermacs-function-or-region-explain`.
=> fix: don't switch to aider buffer before reading symbol

aidermacs.el
This fixes a stacktrace when calling aidermacs from a project that hasn't been started yet.
=> Check for non-nil `(project-current)` before calling `(project-root)`

aidermacs-backend-vterm.el
Current vterm processing is inefficient due to forced rendering on every check. This change optimizes performance by rendering only when necessary and checking output more intelligently.
The commit also adds a multiline input mode for vterm, allowing users to compose and edit complex commands before sending them. This addresses the limitation of vterm's single-line input model while maintaining the interactive terminal experience.
Key changes:
- Reduce unnecessary vterm rendering to improve performance
- Implement smarter prompt detection with error handling
- Add multiline input mode with configurable key bindings
- Improve resource management with cleanup hooks
=> Optimize vterm output handling and add multiline input support

aidermacs-backend-comint.el
When there is a search/replace block inside an mode-less code fence, The regex was matching on wrong line and not returning the correct major mode.
=> Fix syntax highlighting when code fence does not have mode

README.md, aidermacs-backend-comint.el, aidermacs-backend-vterm.el, aidermacs-backends.el, aidermacs-models.el, aidermacs.el
The long-awaited feature...
After Aidermacs makes modifications, an Ediff window will automatically pop up for a before-and-after comparison. You can use Ediff shortcuts like ‘a’ and ‘b’ to revert to the pre-modification state, or manually edit the buffer to fine-tune the content. This is far more powerful than simply choosing accept/reject.. the Emacs ecosystem truly rocks!
Will close #43 and tninja/aider.el#98
WIP.
=> Use Ediff to Show Better Code Changes

aidermacs.el
aider 进程可能被杀死（/quit），这里少了这个边界判断。
=> fix: the aider process may had been killed

aidermacs-models.el
跳过HTTP headers，确保 json-read 能够读到完整的 response body
=> fix(aidermacs-models): ensure correct parsing by moving to end of headers

README.md, aidermacs-backends.el, aidermacs.el
This commit adds support for using aidermacs via tramp. Interestingly enough the functionality was written almost completely with aider. Wild times!
The main things are:
1. Processing file names before sending them to commands like `/add`, `/read`, etc.
2. Handling output from `/ls` related commands to handle remote files
I've tested the following (in a tramp session):
- Starting a tramp session
- Adding a file
- Adding current file
- Removing a file
- Removing current file
- Listing files
=> Add Tramp Support

aidermacs-backend-vterm.el
I wrote some nifty code to make aider's colors match the currently active emacs theme. Only works for the vterm backend, and currently only sets a few foreground colors. Completion colors are currently not set.
=> Match emacs theme in vterm backend

aidermacs-backends.el
This adds a hook to run before starting the backend; this allows for custom setup like setting env-vars.
One use case is the injecting of secrets without having to store those secrets in your dotfiles:
Example:
`(add-hook 'aidermacs-before-run-backend-hook (lambda ()
(setenv "OPENAI_API_KEY"
(password-store-get "code/openai_api_key"))))`
=> add hook to run before running backend

aidermacs-backend-comint.el, aidermacs-backend-vterm.el, aidermacs-backends.el, aidermacs-models.el, aidermacs.el
The defcustom calls were missing the :group argument. By adding this we can see all customization options with `M-x customize-group aidermacs`.
=> add options to groups

aidermacs.el
Hi. It's really important to me for Aidermacs to save the queries I send across Emacs sessions. That way if I kill Emacs, I don't have to write my prompts all over again.
=> feat: add history for aidermacs read-string inputs

aidermacs.el
Now that there's another command for adding current file to session, the `aidermacs-add-file` doesn't need to auto-complete the current file name. Most of the time the user uses this command is trying to add other files.
=> Do not insert file name when adding file to session

README.md
Thank you for creating this useful package!
This PR clarifies that `aidermacs-architect-model` and `aidermacs-editor-model` only inherit from `aidermacs-default-model` during initial initialization. Changing `aidermacs-default-model` after package load does not affect these variables.
The current README doesn't seem to make this behavior clear, which leads to unexpected model configuration. I believe this addresses Issue #37, as I experienced the same problem when changing the default model after package initialization.
=> Improve model configuration documentation

aidermacs-backend-comint.el
fixes #50
The issue here is that diff-mode by default will try and update the line numbers in the headers on the fly. But this leads to the font lock buffer and the actual buffer getting out of sync. For example if it changes from
```diff
@@ -1,36 +1,3 @@
```
to
```diff
@@ -1,9 +1,0 @@
```
The two positions will now be off by 1 (because 36 was changed to 9). To fix we disable this behavior.
=> Don't update diff headers in font lock

README.md, aidermacs-models.el, aidermacs.el
Fixed the model selection behavior described in #86.
Now when users set aidermacs-default-model, the change is automatically reflected in architect/editor models unless they're explicitly configured with their own values.
- Change architect/editor/weak model defaults from direct reference to nil
- Add getter functions to dynamically fall back to aidermacs-default-model
- Update aidermacs-run to use these getter functions
- Update README to reflect the new model inheritance behavior
=> Fix model inheritance to dynamically use default model values

README.md
I accidentally removed these from the main "Getting Started" block when adding the spacemacs section, sorry!
=> readme: add back steps 4 and 5 to getting started

README.md
Tiny fix, but I was just going through the Aider docs and found this to be out of sync with them, so I updated it accordingly! Coming from Haskell, knowing that there is support for `--` also is nice :).
=> Fix the part about the "AI" comments in the README.md

aidermacs.el
Currently, user input (user-command) must be non-empty for it to be concatenated with prompt-prefix and context. Otherwise, only the command (e.g., `/code`, `/architecture`...) is sent to aider, effectively doing nothing.
This is confusing when the prompt-prefix is sufficient to form the complete prompt, such as with `aidermacs-write-unit-test`. The user must enter something for the prompt to be formed and sent; otherwise, only `/architect` is sent.
This change simplifies the logic in `aidermacs--form-prompt`. It will always use prompt-prefix and context. If these variables are nil, `concat` will ignore them.
=> aidermacs--form-prompt: Always use prompt-prefix and context.

aidermacs-models.el
There are circumstances, e.g. when using ollama, where aider will not give us a correct list of models, instead providing some defaults that nobody uses anymore (llama2 etc). Requiring an exact match in this case blocks users from selecting the model they wish to select.
Ref:
https://github.com/Aider-AI/aider/issues/3081
https://github.com/Aider-AI/aider/pull/3944
=> Do not require exact matches when selecting models

aidermacs-backend-comint.el, aidermacs-backend-vterm.el, aidermacs.el
This can occur when e.g. the autoupdate prompt runs - we send a command, aider is expecting a yes/no, the command doesn't run and comint sometimes throws some error. Instead, ask the user to resolve whatever aider is asking of them first.
=> Don't send commands to aider if it's not ready for them

aidermacs.el
completing-read doesn't let the user enter a prompt that isn't in aidermacs--common-prompts (well, it can, but you sacrifice your ability to use the space key)
A reasonable compromise between making it usable when you don't want to use one of the preselected prompts and still having completion might be pre-populating the history with `aidermacs-common-prompts`, but I've kept it out of this MR.
=> Use read-from-minibuffer instead of completing-read for prompts

aidermacs.el
In a temp buffer, the current `exec-path` is not inherited from the current buffer. This causes problems with packages like
[envrc](https://github.com/purcell/envrc). Currently, if I install aider inside a direnv environment, `aidermacs-aider-version` fails.
This PR fix this by copying the current `exec-path` and setting it inside the temp buffer environment. 
Something like this was done in the rust-mode package: [example pull request](https://github.com/rust-lang/rust-mode/pull/470)
Also, this won't impact other users
=> Fix temp buffer exec path

README.md, aidermacs.el
- Add new defcustom `aidermacs-default-chat-mode` with choices: nil/code, ask, architect, help
- Re-add `aidermacs-use-architect-mode` as an obsolete boolean defcustom
- When non-nil and the new option is unset, translate to `'architect` and emit a warning
- Refactor `aidermacs-run`
- Early translate legacy flag
- Build backend args from the new chat-mode logic
- Remove architect-specific code path
- Store `startup-mode` buffer-locally
- Update docstrings and customization groups
BREAKING CHANGE: `aidermacs-use-architect-mode` will be removed in a future release. Replace any uses with `(setq aidermacs-default-chat-mode 'architect)`.
=> feat(core)!: introduce `aidermacs-default-chat-mode`; deprecate `aidermacs-use-architect-mode`

aidermacs.el
Fixes diffs not working because `aidermacs--command-may-edit-files` would always return nil and `aidermacs--prepare-for-code-edit` would not be called.
=> fix default chat mode: defaults to 'code

aidermacs.el
When checking aider version, use `process-file` so that when working with a repo over tramp it will run aider on the remote system. I verified that with this change aider can be started both on local repo and also remote via tramp.
=> Fix: Use process-file to get aider version. Fixes #155

aidermacs.el
the backend sometimes takes a little longer to start (happens to me several times). increase the total wait time while also decreasing the check interval
=> Wait for a bit longer time for the backend to be ready
